const type = {
    NotoSansBlack: 'NotoSans-Black',
    NotoSansBlackItalic: 'NotoSans-BlackItalic',
    NotoSansBold: 'NotoSans-Bold',
    NotoSansBoldItalic: 'NotoSans-BoldItalic',
    NotoSansExtraBold: 'NotoSans-ExtraBold',
    NotoSansExtraBoldItalic: 'NotoSans-ExtraBoldItalic',
    NotoSansExtraLight: 'NotoSans-ExtraLight',
    NotoSansExtraLightItalic: 'NotoSans-ExtraLightItalic',
    NotoSansItalic: 'NotoSans-Italic',
    NotoSansLight: 'NotoSans-Light',
    NotoSansLightItalic: 'NotoSans-LightItalic',
    NotoSansMedium: 'NotoSans-Medium',
    NotoSansMediumItalic: 'NotoSans-MediumItalic',
    NotoSansRegular: 'NotoSans-Regular',
    NotoSansSemiBold: 'NotoSans-SemiBold',
    NotoSansSemiBoldItalic: 'NotoSans-SemiBoldItalic',
    NotoSansThin: 'NotoSans-Thin',
    NotoSansThinItalic: 'NotoSans-ThinItalic',
};
export default{type}